/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductCategoriesRouteImport } from './routes/admin.product-categories'
import { Route as AdminMedicinesRouteImport } from './routes/admin.medicines'
import { Route as AdminMedicineLibraryRouteImport } from './routes/admin.medicine-library'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminImportsRouteImport } from './routes/admin.imports'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductCategoriesRoute = AdminProductCategoriesRouteImport.update({
  id: '/product-categories',
  path: '/product-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedicinesRoute = AdminMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedicineLibraryRoute = AdminMedicineLibraryRouteImport.update({
  id: '/medicine-library',
  path: '/medicine-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportsRoute = AdminImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/medicine-library': typeof AdminMedicineLibraryRoute
  '/admin/medicines': typeof AdminMedicinesRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/medicine-library': typeof AdminMedicineLibraryRoute
  '/admin/medicines': typeof AdminMedicinesRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/medicine-library': typeof AdminMedicineLibraryRoute
  '/admin/medicines': typeof AdminMedicinesRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/imports'
    | '/admin/inventory'
    | '/admin/medicine-library'
    | '/admin/medicines'
    | '/admin/product-categories'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/stores'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/imports'
    | '/admin/inventory'
    | '/admin/medicine-library'
    | '/admin/medicines'
    | '/admin/product-categories'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/stores'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/imports'
    | '/admin/inventory'
    | '/admin/medicine-library'
    | '/admin/medicines'
    | '/admin/product-categories'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/stores'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-categories': {
      id: '/admin/product-categories'
      path: '/product-categories'
      fullPath: '/admin/product-categories'
      preLoaderRoute: typeof AdminProductCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medicines': {
      id: '/admin/medicines'
      path: '/medicines'
      fullPath: '/admin/medicines'
      preLoaderRoute: typeof AdminMedicinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medicine-library': {
      id: '/admin/medicine-library'
      path: '/medicine-library'
      fullPath: '/admin/medicine-library'
      preLoaderRoute: typeof AdminMedicineLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/imports': {
      id: '/admin/imports'
      path: '/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AdminImportsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminImportsRoute: typeof AdminImportsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMedicineLibraryRoute: typeof AdminMedicineLibraryRoute
  AdminMedicinesRoute: typeof AdminMedicinesRoute
  AdminProductCategoriesRoute: typeof AdminProductCategoriesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportsRoute: AdminImportsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMedicineLibraryRoute: AdminMedicineLibraryRoute,
  AdminMedicinesRoute: AdminMedicinesRoute,
  AdminProductCategoriesRoute: AdminProductCategoriesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
